#!/usr/bin/env python3
"""
Example: Training with precomputed augmented dataset (memory-efficient!)

Shows how to use the precomputed augmented dataset generated by precompute_augmented.py
Uses memory-mapped loading to train on large datasets without loading into RAM
"""

import torch
from Moisturizer import MeteoGaliciaCollector, SoilMoistureSequenceDataset

def main():
    print("=" * 70)
    print("TRAINING WITH PRECOMPUTED AUGMENTED DATASET")
    print("=" * 70)

    # 1. Load the precomputed augmented dataset
    collector = MeteoGaliciaCollector()

    print("\n1. Loading precomputed augmented dataset...")
    print(f"   This uses memory-mapped arrays - won't load ~240GB into RAM!")

    dataset = SoilMoistureSequenceDataset(
        timeseries=str(collector.timeseries_file),
        stations=str(collector.stations_file),
        nearest=str(collector.nearest_file),
        seq_length=64,
        n_nearest=4,  # Augmented dataset uses 4 nearby stations
        feature_params=None,  # Will be loaded from precomputed data
        precomputed_path=str(collector.data_dir / "precomputed_sequences_augmented.npz"),
        normalize=False,  # Data is already pre-normalized!
        norm_stats_path=str(collector.data_dir / "normalization_stats_augmented.npz")
    )

    print(f"   Loaded {len(dataset)} augmented samples")
    print(f"   Memory usage: Minimal! (only batches are loaded into RAM)")

    # 2. Split into train/val/test
    print("\n2. Splitting dataset...")
    # The augmented dataset has each base sample augmented 120 times
    # We want to ensure base samples don't leak between splits

    # Option A: Simple split (augmentations may leak between splits)
    train_dataset, val_dataset, test_dataset = dataset.train_val_test_split(
        train_fraction=0.7,
        val_fraction=0.15,
        test_fraction=0.15
    )

    print(f"   Train: {len(train_dataset):,} samples")
    print(f"   Val: {len(val_dataset):,} samples")
    print(f"   Test: {len(test_dataset):,} samples")

    # 3. Create DataLoaders with optimized settings
    print("\n3. Creating DataLoaders...")
    print(f"   Tip: Use fewer num_workers to save RAM (workers share memory-mapped data)")

    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=256,  # Adjust based on GPU memory
        shuffle=True,
        num_workers=4,   # Fewer workers since we're not doing on-the-fly augmentation
        pin_memory=True,
        persistent_workers=True,
        prefetch_factor=2  # Lower prefetch since data is already fast
    )

    val_loader = torch.utils.data.DataLoader(
        val_dataset,
        batch_size=512,  # Can be larger for validation
        shuffle=False,
        num_workers=2,
        pin_memory=True
    )

    test_loader = torch.utils.data.DataLoader(
        test_dataset,
        batch_size=512,
        shuffle=False,
        num_workers=2,
        pin_memory=True
    )

    print(f"   Train batches: {len(train_loader):,} (batch_size=256)")
    print(f"   Val batches: {len(val_loader):,} (batch_size=512)")
    print(f"   Test batches: {len(test_loader):,} (batch_size=512)")

    # 4. Inspect a sample
    print("\n4. Inspecting sample...")
    sample = dataset[0]
    print(f"   Features shape: {sample['features'].shape}")  # [seq_length, features]
    print(f"   Target shape: {sample['target'].shape}")
    print(f"   Mask shape: {sample['mask'].shape}")
    print(f"   Data is pre-normalized: values in [-1, 1] range")

    # 5. Test data loading speed
    print("\n5. Testing data loading speed...")
    print(f"   Loading first batch...")
    import time
    start = time.time()
    batch = next(iter(train_loader))
    elapsed = time.time() - start
    print(f"   First batch: {elapsed:.3f}s (includes initialization)")

    start = time.time()
    batch = next(iter(train_loader))
    elapsed = time.time() - start
    print(f"   Second batch: {elapsed:.3f}s (should be faster)")

    # 6. Example training loop snippet
    print("\n6. Example training loop:")
    print("""
    # Your model initialization
    model = YourModel(input_features=138, seq_length=64)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    for epoch in range(num_epochs):
        # Training
        model.train()
        for batch_idx, batch in enumerate(train_loader):
            features = batch['features']  # [batch_size, 64, 138]
            targets = batch['target']     # [batch_size, 1]
            mask = batch['mask']          # [batch_size, 64, 138]

            # Forward pass
            predictions = model(features, mask)
            loss = criterion(predictions, targets)

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if batch_idx % 100 == 0:
                print(f"Epoch {epoch}, Batch {batch_idx}, Loss: {loss.item():.4f}")

        # Validation
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for batch in val_loader:
                features = batch['features']
                targets = batch['target']
                mask = batch['mask']

                predictions = model(features, mask)
                val_loss += criterion(predictions, targets).item()

        val_loss /= len(val_loader)
        print(f"Epoch {epoch}, Val Loss: {val_loss:.4f}")

    # Final test evaluation
    model.eval()
    test_loss = 0
    with torch.no_grad():
        for batch in test_loader:
            features = batch['features']
            targets = batch['target']
            mask = batch['mask']

            predictions = model(features, mask)
            test_loss += criterion(predictions, targets).item()

    test_loss /= len(test_loader)
    print(f"Final Test Loss: {test_loss:.4f}")
    """)

    print("\n" + "=" * 70)
    print("✓ READY TO TRAIN!")
    print("=" * 70)
    print("\nKey advantages of precomputed augmented dataset:")
    print("  ✓ 120x larger dataset (each base sample × 120 augmentations)")
    print("  ✓ Minimal RAM usage (memory-mapped, only batches loaded)")
    print("  ✓ Pre-normalized (fast loading)")
    print("  ✓ Consistent augmentations across epochs (reproducible)")
    print("  ✓ Fast data loading (no on-the-fly computation)")
    print("\nExpected memory usage:")
    print("  - Dataset loading: <1 GB (memory-mapped)")
    print("  - Per batch: ~1-2 GB (256 samples × 64 × 138 × 4 bytes)")
    print("  - Workers: ~4 GB (4 workers × minimal overhead)")
    print("  - Total: ~5-10 GB for data loading")
    print("  - Plus: Your model and GPU memory")
    print("\nExpected improvements vs non-augmented:")
    print("  - Better spatial generalization (learned position-invariance)")
    print("  - More robust to missing/noisy stations")
    print("  - Better moisture map predictions at unseen locations")
    print("=" * 70)

if __name__ == "__main__":
    main()
